-- AUTOGENERATED FILE PatientList.elm - DO NOT EDIT
-- Update by replacing with output of tools/fakedata.js

module PatientList exposing (..)

import Dict as D exposing (..)
import Patient exposing (..)

patientList : Dict Int Patient
patientList = D.fromList [
  (0 , Patient "Jyot Uvdt" "1964-12-19" "53" )
  ,
  (1 , Patient "Nlap Gekbvs" "1974-2-14" "43" )
  ,
  (2 , Patient "Bwmamnt Drxfz" "2017-12-13" "0" )
  ,
  (3 , Patient "Hyxkgs Yyjx" "1980-1-6" "37" )
  ,
  (4 , Patient "Egmczdr Wxqbwb" "1945-2-28" "72" )
  ,
  (5 , Patient "Kijs Uhch" "1992-1-15" "25" )
  ,
  (6 , Patient "Lcnlmru Rjapjrhc" "2012-5-7" "5" )
  ,
  (7 , Patient "Foaq Ugpgfv" "1958-1-19" "59" )
  ,
  (8 , Patient "Mzfgg Aiac" "2013-7-28" "4" )
  ,
  (9 , Patient "Hxoa Ueewparp" "1918-9-19" "99" )
  ,
  (10 , Patient "Homrbvco Wbkp" "1979-3-26" "38" )
  ,
  (11 , Patient "Ckheghg Nujtxwwt" "1961-1-12" "56" )
  ,
  (12 , Patient "Tvmf Xpvo" "1947-4-31" "70" )
  ,
  (13 , Patient "Ayxdan Izbrcjn" "1922-12-4" "95" )
  ,
  (14 , Patient "Vwpgwq Ohgmzy" "1983-1-20" "34" )
  ,
  (15 , Patient "Alxcxiv Hgfif" "1937-12-31" "80" )
  ,
  (16 , Patient "Kpdo Yjazr" "1972-6-27" "45" )
  ,
  (17 , Patient "Dydb Fvxl" "1940-7-21" "77" )
  ,
  (18 , Patient "Hpbxl Gxwo" "1962-10-11" "55" )
  ,
  (19 , Patient "Xssd Mqnlcx" "1984-7-29" "33" )
  ,
  (20 , Patient "Mvnls Dbfcsh" "1962-8-23" "55" )
  ,
  (21 , Patient "Ibhfq Hzidug" "1993-9-22" "24" )
  ,
  (22 , Patient "Hxohxaxg Fizjg" "1918-8-20" "99" )
  ,
  (23 , Patient "Xgejgyvf Danrzqif" "1936-4-26" "81" )
  ,
  (24 , Patient "Xrwh Szlczfrh" "1928-12-4" "89" )
  ,
  (25 , Patient "Tpukqmzu Etolbve" "1996-6-27" "21" )
  ,
  (26 , Patient "Razjjtf Cbpksu" "2004-6-16" "13" )
  ,
  (27 , Patient "Znhgruvf Uxpui" "1966-12-27" "51" )
  ,
  (28 , Patient "Ylmo Ttqytmfs" "1935-8-28" "82" )
  ,
  (29 , Patient "Jybmcahs Rwugg" "1984-8-10" "33" )
  ]
