-- AUTOGENERATED FILE PatientList.elm - DO NOT EDIT
-- Update by running nodejs fakedata.js *in* tools/

module PatientList exposing (..)

import Dict as D exposing (..)
import Patient exposing (..)

patientList : Dict Int Patient
patientList = D.fromList [
  (0 , Patient "Xfsu Sbslnurq" "1998-3-17" "19" )
  ,
  (1 , Patient "Gtlenzs Tmdgzefy" "1953-2-21" "64" )
  ,
  (2 , Patient "Jzxmxfb Gahz" "1934-8-30" "83" )
  ,
  (3 , Patient "Oshhc Iatfwsl" "1942-4-24" "75" )
  ,
  (4 , Patient "Oelygsg Mqux" "1945-8-12" "72" )
  ,
  (5 , Patient "Bxsljz Yfec" "1982-9-12" "35" )
  ,
  (6 , Patient "Wyajm Kadlb" "1918-9-5" "99" )
  ,
  (7 , Patient "Jjow Vnlkdtfh" "1963-9-22" "54" )
  ,
  (8 , Patient "Nrxf Ejmh" "2002-2-3" "15" )
  ,
  (9 , Patient "Gool Ddmkkip" "1929-8-18" "88" )
  ,
  (10 , Patient "Emtuo Chxihxp" "1990-3-7" "27" )
  ,
  (11 , Patient "Uxdf Xwqwloch" "1994-10-25" "23" )
  ,
  (12 , Patient "Fscln Hilps" "1944-4-23" "73" )
  ,
  (13 , Patient "Pwqqgog Gxgzozz" "1936-12-17" "81" )
  ,
  (14 , Patient "Qhntap Gwncvcpy" "1930-2-11" "87" )
  ,
  (15 , Patient "Akop Jljei" "1988-7-31" "29" )
  ,
  (16 , Patient "Zwhdcz Hfutsjr" "1980-3-31" "37" )
  ,
  (17 , Patient "Tidfgfv Eqjuikkf" "1971-3-6" "46" )
  ,
  (18 , Patient "Tescbkkd Dygcrut" "1925-11-13" "92" )
  ,
  (19 , Patient "Vcgifc Snojchl" "1921-6-6" "96" )
  ,
  (20 , Patient "Vofiq Xjqge" "1981-11-4" "36" )
  ,
  (21 , Patient "Skskc Ifor" "1991-5-24" "26" )
  ,
  (22 , Patient "Gekli Wvgx" "1944-2-3" "73" )
  ,
  (23 , Patient "Snop Tkupismh" "1959-10-6" "58" )
  ,
  (24 , Patient "Klgcbmm Vecg" "2009-2-22" "8" )
  ,
  (25 , Patient "Ounj Xhwof" "1989-1-22" "28" )
  ,
  (26 , Patient "Zkfrkjf Mslc" "1974-9-27" "43" )
  ,
  (27 , Patient "Jrvlbp Ejutft" "1992-3-12" "25" )
  ,
  (28 , Patient "Joif Obbjms" "2004-4-3" "13" )
  ,
  (29 , Patient "Uubdyi Wgtaw" "1996-8-1" "21" )
  ]
