var numPatients=30;
var numJobs=25;

function captext(s) {
    return s.charAt(0).toUpperCase() + s.slice(1);
}

function randomtext() {
    var letters='abcdefghijklmnopqrstuvwxyz'
    var n=3+5*Math.random()
    text=''
    for (var i=0;i<n;i++) {
        text+=letters[Math.floor(Math.random()*letters.length)]
    }
    return text;
}

function mkname() {
    return captext(randomtext())+' '+captext(randomtext());
}

function mkpatient() {
    
    var year=Math.floor(1918+100*Math.random())
    var month=Math.floor(1+12*Math.random())
    var day=Math.floor(1+31*Math.random())
    
    patient={
        'name': mkname(),
        'dob': year+'-'+month+'-'+day,
        'age': 2017-year
    };
    return patient;
}

var jobdesc=['Blood test','Ultrasound','CT scan','MRI scan','Biopsy']
function mkjob() {
    job={
        'patientID':Math.floor(numPatients*Math.random()),
        'job':jobdesc[Math.floor(Math.random()*jobdesc.length)],
        'completed':(Math.random()<0.25)
    }
    return job
}

var patients=[]
for (var i=0;i<numPatients;++i) patients.push(mkpatient());

var jobs=[]
for (var i=0;i<numJobs;++i) jobs.push(mkjob());

console.log('-- AUTOGENERATED FILE PatientList.elm - DO NOT EDIT')
console.log('-- Update by replacing with output of tools/fakedata.js')
console.log('')
console.log('module PatientList exposing (..)')
console.log('')
console.log('import Dict as D exposing (..)')
console.log('import Patient exposing (..)')
console.log('')
console.log('patientList : Dict Int Patient')
console.log('patientList = D.fromList [')

for (var i=0;i<patients.length;i++) {
    if (i!=0) console.log('  ,')
    console.log('  ('+i+' , Patient '+'"'+patients[i]['name']+'" "'+patients[i]['dob']+'" "'+patients[i]['age']+'" )')
}
console.log('  ]')
